# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :qa do
    build_app(scheme: "Staging")
    increment_build_number
 	 update_code_signing_settings(
 		use_automatic_signing: true,
 		path:  "/Users/gtcsysmacmini2/Office/Projects/iOS/learn/CustomApp/CustomApp.xcodeproj"
 	 )
    # build_number = increment_build_number
    # upload_to_testflight
    # add actions here: https://docs.fastlane.tools/actions
  end
  
  lane :beta do
    build_app(scheme: "Dev")
    increment_build_number
    upload_to_testflight
  	 update_code_signing_settings(
  		use_automatic_signing: true,
  		path:  "/Users/gtcsysmacmini2/Office/Projects/iOS/learn/CustomApp/CustomApp.xcodeproj"
  	 )
    # add actions here: https://docs.fastlane.tools/actions
  end
  
  lane :release do
    # build_app(scheme: "CustomApp")
    build_app(scheme: "CustomApp",
                workspace: "CustomApp.xcworkspace",
                include_bitcode: true)
    increment_build_number
  	 update_code_signing_settings(
  		use_automatic_signing: true,
  		path:  "/Users/gtcsysmacmini2/Office/Projects/iOS/learn/CustomApp/CustomApp.xcodeproj"
  	 )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
